### PR TITLE
Uncrustify

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
what do you think about?

### CODE REVIEW

**Comment by koeppea** [comment]
Just revisited this one. 
The intending of pre-processor statements is done using spaces. 
The intending of code block levels is done using unexpanded tab stops.
The intending of manually wrapped long statements seem to be kept with spaces.

With using unexpanded tab stops, we're much far away from the code style rule at the bottom of each file:
```c
/* EOF */

// vim:ts=3:expandtab
```
Can **uncrustify** be configured the same way? If so can you re-run on a fresh state of your branch?

If this is not possible, I'm not a fan of mixing intending characters and wouldn't support this in this case.

**Comment by LocutusOfBorg** [comment]
I don't have an answer, I see lots of things in the example file
http://uncrustify.sourceforge.net/default.cfg
but I don't know how to have the result you want...

**Comment by sgeto** [comment]
A bit unrelated but clang format is a great alternative to uncrustify.

**Comment by koeppea** [comment]
@LocutusOfBorg did you use the default configuration of **uncrustify**?
mainly these values control what I mean:
```
#
# Indenting
#

# The number of columns to indent per level.
# Usually 2, 3, 4, or 8. Default=8
indent_columns                  = 8        # unsigned number

# The continuation indent. If non-zero, this overrides the indent of '(' and '=' continuation indents.
# For FreeBSD, this is set to 4. Negative value is absolute and not increased for each ( level
indent_continue                 = 0        # number

# The continuation indent for func_*_param if they are true.
# If non-zero, this overrides the indent.
indent_param                    = 0        # unsigned number

# How to use tabs when indenting code
# 0=spaces only
# 1=indent with tabs to brace level, align with spaces (default)
# 2=indent and align with tabs, using spaces when not on a tabstop
indent_with_tabs                = 1        # number

# Comments that are not a brace level are indented with tabs on a tabstop.
# Requires indent_with_tabs=2. If false, will use spaces.
indent_cmt_with_tabs            = false    # false/true
```

*indent_columns* should be 3 and *indent_with_tabs* should be 0 AFAICS.

**Comment by LocutusOfBorg** [comment]
I used this one
https://github.com/Ettercap/ettercap/pull/516/commits/70f047af23636de0f1fa34b23c6dfb5510a5bc85
indent_columns is 3 in my case

**Comment by kholia** [comment]
I think clang-format can be a good alternative to Uncrustify.

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

Irrespective of the tool chosen, using a consistent coding style would be great.

**Comment by koeppea** [comment]
Wow. Don't know how a `git push -f ` could close a pull request..... 
Well  opening a new one..... :-/

**Pull request closed without merging**
