### PR TITLE
Fix a heap buffer over-read in ip_addr_cmp function

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/Ettercap/ettercap/issues/746, https://github.com/Ettercap/ettercap/issues/745, and https://github.com/Ettercap/ettercap/issues/747.

I am not familiar with this code. Please review carefully.

### CODE REVIEW

**Comment by eaescob** [comment]
👍

**Comment by koeppea** [comment]
IMHO this fixes only a symptom. 
Because, well initialized *ip_addr* structs have a fixed *addr_len* member value.
I'd like to avoid unecessary processing of such low-level function.
For me, the root cause lies somewhere in the file-reading-engine of etterlog.
Currently suspecting `get_info()` in **el_log.c**. 

When etterlog reads data, it has to revalidate the values for sanity.
I'm thinking of reinitializing *ip_addr* struct as a quick win.

**Comment by eaescob** [comment]
You do have a good point, the comparison is only fixing the symptom of invalid parsing of a log file. But might be worth testing (fuzzing) to see if the  size checks actually come into effect because of other input parsing (parsing packets from pcap/etc).

**Comment by koeppea** [comment]
Parsing / dissecting packets is much more static and quite well checked in comparison to steps
Etterlog's routines. 
Which basically is naturally due to the popularity of the utility.

**Comment by koeppea** [comment]
Closing this PR in favor of #828 .
Thanks though for bringing up the hint to the actual root cause.

**Pull request closed without merging**
