### PR TITLE
502 fix

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by koeppea** [comment]
Ain't we're better off just returning from the function rather than using the BUG_IF macro which aborts the complete execution of ettercap. In the middle of a MITM session it disconnects the targets until they refresh their neighbor cache.
What do you think?

**Comment by LocutusOfBorg** [comment]
thanks @koeppea actually I wondered about the case, and yes, you are right!

I guess I updated it correctly :)

**Comment by koeppea** [comment]
:+1:

**Comment by LocutusOfBorg** [comment]
Merged thanks!

**Pull request merged**
