### PR TITLE
Updated curl and check

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by koeppea** [comment]
Works as expected.

**Comment by LocutusOfBorg** [comment]
thanks! BTW I'm working right not to the libettercap crash fixes :)

**Comment by koeppea** [comment]
> I'm working right not to the libettercap crash fixes

??? "not" or now?
Which one(s) do you mean?

**Comment by LocutusOfBorg** [comment]
#698 answers for me :)

**Comment by koeppea** [comment]
Yes indeed. Now I remember.

**Pull request merged**
