### PR TITLE
Yosemite port forwarding

### PR DESCRIPTION
**Pull request by Ra7t0r**
Please check the port forwarding commands for errors

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
rebase and merge?

**Comment by koeppea** [comment]
I can not test. I just know that the make up of the FreeBSD pfctl support works on FreeBSD. I thought MacOSX also based on FreeBSD at some extend. @panosip: could you PKK please check if the rebased master would now solve this issue on Yosemite as well. Just uncomment the redir commands in the FreeBSD section.

**Comment by koeppea** [comment]
I just rechecked the changes. The execution of the plain echo without piping somewhere doesn't make sense for me. @eascob: could also help out testing this. AFAIK you own a Mac also.

**Comment by LocutusOfBorg** [comment]
@panosip ping!
we are waiting this pull for the new release

**Comment by panosip** [comment]
Hello and sorry for my late response.

In order to use port forwarding on Yosemite, we should try this


1) Create anchor file at: 
 /etc/pf.anchors/com.pfettercap

2) In the com.pfettercap anchor file, enter:
rdr pass on %iface inet proto tcp from any to any port %port -> localhost port %rport

3) Test the anchor file:
sudo pfctl -vnf /etc/pf.anchors/com.pfettercap

4. Add the anchor file to the pf.conf file:
sudo vi /etc/pf.conf

Then add in the following lines under each corresponding section - e.g. the rdr-anchor line under the current rdr-anchor line, and the load anchor under the current load-anchor statement:
rdr-anchor "port80"
load anchor "port80" from "/etc/pf.anchors/com.pfettercap"

5. Load the pf.conf file automatically:
This can be done either manually (see below) or create a dedicated Launch Daemon to load and enable the config on boot, or edit the current daemon for pf to enable the new config automatically at startup:
sudo vi /System/Library/LaunchDaemons/com.apple.pfctl.plist

Then within the section detailing the program arguments:
<key>ProgramArguments</key>

Add in an extra string with -e, which will enable the config, as per:

<string>pfctl</string>
<string>-e</string>
<string>-f</string>
<string>/etc/pf.conf</string>

Then save the file, exit and restart the server to test. 



To test this method manually (no restart required) you can use sudo pfctl -ef /etc/pf.conf which will load and enable the pf.conf file, which will then call the com.papercut anchor file. 

Additionally, if you want to try this out without making any changes to config files, you can test this temporarily (it will not retain the settings after a restart) by running:

echo "
rdr pass on en0 inet proto tcp from any to self port 80 -> 127.0.0.1 port 9191
rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 9191
rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 9191
" | sudo pfctl -ef -    

via papercut.com

**Comment by LocutusOfBorg** [comment]
the question was: can you please try the latest git master and uncomment the section "freebsd" to try if it does work for macosx too?

thanks!

**Comment by panosip** [comment]
I got this error multiple times:

WARNING: [/tmp/ettercap-mXSXpW/ettercap-0.8.1/src/ec_sslwrap.c:sslw_insert_redirect:398]

 Cannot setup http redirect (command: the_script_described_above), please edit your etter.conf file and put a valid value in redir_command_on field

**Comment by koeppea** [comment]
Could you please share the content of the ettercap-debug log?

**Comment by koeppea** [comment]
> echo "
> rdr pass on en0 inet proto tcp from any to self port 80 -> 127.0.0.1 port 9191
> rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 9191
> rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 9191
> " | sudo pfctl -ef -

This is actually what the freebsd command is doing (besindes the *sudo*). So I'm very curious about the debug content. Somewhere is the reason of this. The syntax of FreeBSD and this is identical. So it should work the same way.

**Comment by koeppea** [comment]
You could as come into IRC #ettercap-project

**Comment by ayan-das1234** [comment]
please fix the build isssue while installing ettercap with homebrew, homebrew installs ettercap with old build files which don't have support for pfctl

**Comment by koeppea** [comment]
So finally getting back to this PR to prove my thesis mentioned on 30 Dec 2014.

## 1. Test the meanwhile current redir_commands as defined in [master](https://github.com/Ettercap/ettercap/blob/master/share/etter.conf.v4#L189):

 1. PF NAT rules before ettercap is started:
```
MacBook-Pro:ettercap koeppea$ sudo pfctl -sn
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
MacBook-Pro:ettercap koeppea$ 
```

 2. PF NAT rules while ettercap is running with enabled redir_commands:
```
MacBook-Pro:ettercap koeppea$ sudo pfctl -sn
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
rdr pass on en0 inet proto tcp from any to any port = 992 -> 127.0.0.1 port 59263
rdr pass on en0 inet6 proto tcp from any to any port = 992 -> ::1 port 59263
rdr pass on en0 inet proto tcp from any to any port = 465 -> 127.0.0.1 port 59264
rdr pass on en0 inet6 proto tcp from any to any port = 465 -> ::1 port 59264
rdr pass on en0 inet proto tcp from any to any port = 995 -> 127.0.0.1 port 59265
rdr pass on en0 inet6 proto tcp from any to any port = 995 -> ::1 port 59265
rdr pass on en0 inet proto tcp from any to any port = 563 -> 127.0.0.1 port 59266
rdr pass on en0 inet6 proto tcp from any to any port = 563 -> ::1 port 59266
rdr pass on en0 inet proto tcp from any to any port = 636 -> 127.0.0.1 port 59267
rdr pass on en0 inet6 proto tcp from any to any port = 636 -> ::1 port 59267
rdr pass on en0 inet proto tcp from any to any port = 994 -> 127.0.0.1 port 59268
rdr pass on en0 inet6 proto tcp from any to any port = 994 -> ::1 port 59268
rdr pass on en0 inet proto tcp from any to any port = 993 -> 127.0.0.1 port 59269
rdr pass on en0 inet6 proto tcp from any to any port = 993 -> ::1 port 59269
rdr pass on en0 inet proto tcp from any to any port = 8080 -> 127.0.0.1 port 59270
rdr pass on en0 inet6 proto tcp from any to any port = 8080 -> ::1 port 59270
rdr pass on en0 inet proto tcp from any to any port = 443 -> 127.0.0.1 port 59271
rdr pass on en0 inet6 proto tcp from any to any port = 443 -> ::1 port 59271
rdr pass on en0 inet proto tcp from any to any port = 990 -> 127.0.0.1 port 59272
rdr pass on en0 inet6 proto tcp from any to any port = 990 -> ::1 port 59272
MacBook-Pro:ettercap koeppea$ 
```
 3. PF NAT rules after ettercap has been gracefully quit:
```
MacBook-Pro:ettercap koeppea$ sudo pfctl -sn
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
MacBook-Pro:ettercap koeppea$ 
```

The output of the ettercap session:
```

MacBook-Pro:~ koeppea$ sudo ettercap -Tqien0
Password:

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

Error Opening file /usr/local/var/GeoIP/GeoIP.dat
Error Opening file /path/to/GeoIP.dat
Listening on:
   en0 -> F4:5C:89:C9:45:15
	  172.21.21.40/255.255.255.0
	  2001:db8:7011:47f6:1f8a:931d/64
	  2001:db8:413:57ad:771f:6440/64
	  fe80::45:a929:9c49:a950/64

Privileges dropped to EUID 0 EGID 0...

  33 plugins
  42 protocol dissectors
  57 ports monitored
20530 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Randomizing 255 hosts for scanning...
Scanning the whole netmask for 255 hosts...
* |==================================================>| 100.00 %

7 hosts added to the hosts list...
Starting Unified sniffing...


Text only Interface activated...
Hit 'h' for inline help

Closing text interface...


Terminating ettercap...
Unified sniffing was stopped.

MacBook-Pro:~ koeppea$ 
```

### Result 
The session runs as expected and the NAT rules get inserted and removed as intended.


## 2. Test the proposed redir_command as of [this pull request](https://github.com/Ettercap/ettercap/pull/641/files#diff-78791b91587e332a28de0d5d496ee352R186) instead:
 1. PF NAT rules  before ettercap is started:
```
MacBook-Pro:ettercap koeppea$ sudo pfctl -sn
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
MacBook-Pro:ettercap koeppea$ 
```

 2. PF NAT rules while ettercap is running with enabled redir_commands:
```
MacBook-Pro:ettercap koeppea$ sudo pfctl -sn
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
MacBook-Pro:ettercap koeppea$ 
```

 3. PF NAT rules after ettercap has been gracefully quit:
```

MacBook-Pro:ettercap koeppea$ sudo pfctl -sn
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
MacBook-Pro:ettercap koeppea$ 
```
The output of the ettercap session:
```


MacBook-Pro:~ koeppea$ 
MacBook-Pro:~ koeppea$ sudo ettercap -Tqien0

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

Error Opening file /usr/local/var/GeoIP/GeoIP.dat
Error Opening file /path/to/GeoIP.dat
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 992 -> localhost port 59263
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 465 -> localhost port 59264
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 995 -> localhost port 59265
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 563 -> localhost port 59266
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 636 -> localhost port 59267
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 994 -> localhost port 59268
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 993 -> localhost port 59269
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 8080 -> localhost port 59270
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 443 -> localhost port 59271
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_insert_redirect:422]

 sslwrap: cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?
 

rdr pass on en0 inet proto tcp from any to any port 990 -> localhost port 59272
Listening on:
   en0 -> F4:5C:89:C9:45:15
	  172.21.21.40/255.255.255.0
	  2001:db8:7011:47f6:1f8a:931d/64
	  2001:db8:413:57ad:771f:6440/64
	  fe80::45:a929:9c49:a950/64

Privileges dropped to EUID 0 EGID 0...

  33 plugins
  42 protocol dissectors
  57 ports monitored
20530 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Randomizing 255 hosts for scanning...
Scanning the whole netmask for 255 hosts...
* |==================================================>| 100.00 %

7 hosts added to the hosts list...
Starting Unified sniffing...


Text only Interface activated...
Hit 'h' for inline help

Closing text interface...


Terminating ettercap...
Unified sniffing was stopped.

WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
WARNING: [/Users/koeppea/dev/ettercap/src/ec_sslwrap.c:sslw_remove_redirect:505]

 sslwrap: cannot remove the redirect for IPv6, did you uncommend the redir6_command_off command in your etter.conf file? 

pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
0 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
MacBook-Pro:~ koeppea$ 
```


### Result 

The session just outputs the echo’s from the redir_command_on and during quit, we find the `pfctl` warning output resulting from the `pfctl -F all -f /etc/pf.conf` command (redir_command_off).

## Conclusion

This proves, that this PR is not useful hence closing w/o merge.
@Ra7t0r I’m sorry to withdraw your efforts creating this pull request.

**Pull request closed without merging**
