### PR TITLE
Update changelog for new release

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by koeppea** [comment]
This pull is for the website right?
We need another one for the code?

**Comment by LocutusOfBorg** [comment]
yep the previous #643 :-)

**Comment by koeppea** [comment]
Oups missed that

**Comment by eaescob** [comment]
Merge the two pending PR's and update?

**Comment by LocutusOfBorg** [comment]
lets release on march, 6? still wondering about #641

**Comment by koeppea** [comment]
Yes. OK by me.
The pull request didn't experience any update since my last comment in it. Hence it's still valid.

**Comment by LocutusOfBorg** [comment]
released folks! Congratulations! :D

**Pull request merged**
