### PR TITLE
Added execreplace filter function

### PR DESCRIPTION
**Pull request by mephesto1337**
Added command `execreplace(COMMAND)`. It acts as:
```
log(DATA.data, "/tmp/output");
drop();
inject("cat /tmp/output | COMMAND");
exec("rm -f /tmp/output");
```

### CODE REVIEW

**Comment by koeppea** [comment]
This is a great contribution. Can you please put it under 0.8.4 CHANGELOG entries. 
Thanks.

**Comment by koeppea** [comment]
Could you please check the warning that comes up when building in Debug mode:

```
[ 26%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_filter.c.o
/home/koeppea/dev/ettercap/src/ec_filter.c: In function ‘func_execreplace’:
/home/koeppea/dev/ettercap/src/ec_filter.c:924:48: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
        char *const argv[] = { "/bin/sh", "-c", (const char*)fop->op.func.string };
                                                ^
```

Thanks.

**Comment by koeppea** [comment]
I've run a test with the filter example from _etter.filter.examples_.
The modified packet doesn't contain the actual payload and also the UDP length is the same as in the original packet:
grafik

[execreplace-test-01.zip](https://github.com/Ettercap/ettercap/files/4410544/execreplace-test-01.zip)

Can you check? Did it work for you?

**Comment by mephesto1337** [comment]
I removed the warning and I'll check the length computation tomorrow.
I only tested with a TCP stream, and the length was increased.

**Comment by mephesto1337** [comment]
So I checked the length issue. It turns out, there is the same with this script:
```
if (udp.dst == 53 && pcre_regex(DATA.data, ".*\x03com\x00.*")) {
    replace("\x03com\x00", "\x02my\x04page\x02de\x00");
    msg("faked");
}
```

I Noticed that udph->ulen is not updated when packet is changed. So I Added :
```c
ORDER_ADD_SHORT(udp->ulen, PACKET->DATA.delta);
```

At the end of `FUNC_DECODER(decode_udp)`, right before the checksum updates.
Should I add this patch in the current PR or open another one ?

Regards,
Thomas

**Comment by koeppea** [comment]
Please add it to this PR.
Thanks.

**Comment by koeppea** [comment]
Looks better now..... unfortunately only for IPv4. UDP packets over IPv6 apparently doesn't get the length effectively changed.
grafik

However I don't see the issue for now....

**Comment by koeppea** [comment]
Seems another issue in the IPv6 protocol decoder. The following patch should fix that:
```diff
diff --git a/src/protocols/ec_ip6.c b/src/protocols/ec_ip6.c
index af091c93..693b8fe8 100644
--- a/src/protocols/ec_ip6.c
+++ b/src/protocols/ec_ip6.c
@@ -181,7 +181,7 @@ FUNC_DECODER(decode_ip6)
    /* XXX - recheck this */
    if(!EC_GBL_OPTIONS->unoffensive && !EC_GBL_OPTIONS->read && (PACKET->flags & PO_FORWARDABLE)) {
       if(PACKET->flags & PO_MODIFIED) {
-         ORDER_ADD_SHORT(PACKET->L3.payload_len, PACKET->DATA.delta);
+         ORDER_ADD_SHORT(ip6->payload_len, PACKET->DATA.delta);
 
          /*
           * In case some upper level encapsulated ip6 decoder
@@ -191,7 +191,7 @@ FUNC_DECODER(decode_ip6)
          PACKET->L3.len = IP6_HDR_LEN;
          PACKET->L3.payload_len = ntohs(ip6->payload_len);
 
-         PACKET->fwd_len = PACKET->L3.payload_len + PACKET->L3.len;
+         PACKET->fwd_len = ntohs(ip6->payload_len) + IP6_HDR_LEN;
       }
    }

```

**Comment by koeppea** [comment]
Do you want to include this IPv6 length delta fix in your PR?
Otherwise this PR can be merged and I'll create a dedicated for the IPv6 fix.

**Comment by mephesto1337** [comment]
I added your change and also added an entry in the CHANGELOG

**Comment by koeppea** [comment]
Merged. Thanks.

**Pull request merged**
