### PR TITLE
Fixing Lack of Sanity checks for malloc() calls

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by gvanem** [comment]
I have an itch with the use of some Gtk memory. In *interfaces/gtk/ec_gtk_conf.c*, the allocated `filename`:
```
   filename = g_build_filename(path, "ettercap_gtk", NULL);
```
should be freed by Gtk. Hence:
```
@@ -103,7 +103,7 @@
       fclose(fd);
    }

-   free(filename);
+   g_free(filename);
    filename = NULL;
 }
```
Prior to this patch, it caused a crash here since I mixed debug/release mode in Ettercap.

(I add this as a comment here instead of openng a new issue).

**Comment by dogbert2** [comment]
That makes sense, g_free() is the better option, rather than free() since
it is in GTK (my bad)...

**Comment by LocutusOfBorg** [comment]
applied thanks!

**Comment by LocutusOfBorg** [comment]
#677

**Pull request merged**
