### PR TITLE
Improvements for GeoIP support

### PR DESCRIPTION
**Pull request by sgeto**
- GeoIP support should be optional
- Better feedback for when GeoIP is found (or not found)
- Use HAVE_GEOIP instead of WITH_GEOIP in *.c source files (which is much more common)
- Also look for GeoIP.h. Because if not, users may confuse it with GeoIP's successor GeoIP2
- Use a cmake find module

### CODE REVIEW

**Comment by eaescob** [comment]
👍

**Comment by sgeto** [comment]
@koeppea 
I'm not sure I'm following.
Do you want me to come after some GeoIP related warnings?
And when is ettercap crashing? When opening the connections table in the GUI?
I've seen some crashes here and there in the GUI, but I don't (or can't) see the relationship with GeoIP.

**Comment by koeppea** [comment]
I've not yet deeply analyzed why but when I merge your pull request over
the latest master from upstream I get warnings when I enable GeoIP
support using the introduced -DENABLE_GEOIP=ON Cmake switch.

They haven't been there before, and warnings typically give a hint of
much more ugly errors. Check Travis' build results. There you can also
see the warnings, however the build doesn't fail, which is why Travis
reports "green".

When I then start ettercap in GTK mode and open a widget that includes
any GeoIP information, it crashes - again only when I compile this pull
request and enable GeoIP support in Cmake.

Don't you see these warnings when compiling on Windows? Of course, you
need to have -DCMAKE_BUILD_TYPE=Debug set to see the warnings.

I just say that, once you fixed the warnings, you've acutally fixed the
problem in GTK mode. For me it looks like a tiny flaw in the
pre-processor statements.

Cheers Alex

**Comment by sgeto** [comment]
Sooo...
You were right. I forget one to change the pre-processor directive in `ec_geoip.h`.
Should be all good now. @koeppea can you check again?

**Comment by gvanem** [comment]
I've been playing with Geoip and Lua lately. With this simple patch:
```diff
--- a/src/lua/share/core/ettercap_ffi.lua 2016-08-25 15:47:39
+++ b/src/lua/share/core/ettercap_ffi.lua 2018-01-09 12:09:48
@@ -264,6 +264,10 @@
 size_t tcp_create_ident(void **i, struct packet_object *po);
 int tcp_find_direction(void *ids, void *id);
 int session_get(struct ec_session **s, void *ident, size_t ident_len);
+
+const char *geoip_ccode_by_ip(struct ip_addr *a);
+const char *geoip_contry_by_ip(struct ip_addr *a);
+
 ]]

 return ettercap_ffi
```
it was quite easy to create this little [`geoip_demo.lua`](https://github.com/Ettercap/ettercap/files/1615203/geoip_demo.lua.txt) script to test with (drop the `.txt` and store to `/share/lua`).

But the problem is that if ettercap was built w/o `WITH_GEOIP`, this script fails to run. Maybe these `geoip_*()` functions could be empty stubs just for this reason? Ali, can you change your PR to do this?

**Comment by sgeto** [comment]
> can you change your PR to do this?

Most definitely! Looks great, I'll test it and get back to you.

> The time here is 14:59!

So strange...😆 
Is your timezone GMT +3?
Mine is. So my timestamps should be just like yours.
Again, let me check and get back to you.

**Comment by gvanem** [comment]
> Is your timezone GMT +3?
> Mine is. So my timestamps should be just like yours.

No Arab dude :-). I'm in Norway (CET). But `%TZ%` has nothing to do with it. The `struct timeval` comes from WinPcap's `npf.sys` (deep inside some very messy kernel-code). Note, the timesttamp does *not* drift (as has been reported elsewhere). It's just reports 9 hours wrong with high precision otherwise.

And changing the Registry key `HKLM\SYSTEM\CurrentControlSet\Services\NPF\TimestampMode` does not help. I think those Italians at CACE-Tech/Riverbed changed it to do nothing some years ago 🤕 . I'll maybe try [Win10Pcap](http://www.win10pcap.org/) or [Npcap](https://github.com/nmap/npcap/releases) next?

But I'm not sure if NPcap is stable enough; it BSoD'ed my machine 2 years ago and I still read users at the Nmap-list have problems with it. Have you tried it lately?

**Comment by sgeto** [comment]
> deep inside some very messy kernel-code

Very messy indeed. I thought I was alone with that opinion.

I don't get BSODs with Win10Pcap but it's not nice either. The project is inactive and has a lot of issues (I currently can't enumerate my adapters except Ethernet and I keep getting `FATAL Bad Memory Block.` errors when trying to inject a packet).

NPcap is not great but at least they're trying.
I didn't believe it was possible, but their code is even messier than Wpcap's (lots of dead code, C and C++ mixed together, no tests/samples, and they lowered the warning level from `Werror `to `W3` **on a kernel module!**)
I get BSODs when trying the Wifi monitor mode. They should have labeled it **experimental**.
It's also worth mentioning that installing the kernel module is a nightmare. In fact, it's only possible with the help of the NPcap installer, which they hide in a private repo.

Nonetheless, as long as you avoid the new and shiny features (Wifi monitor mode), their packet driver API is the best one available these days. You should give it another try.

I use [my own](https://github.com/sgeto/Packet32) packet driver API, which is a fork of NPcap (A work in progress. I need to finalize and push lots of local changes). And no, I don't care what their EULA has to say about that. 👅

**Comment by gvanem** [comment]
Cool! Will check it out.
*Your* `README.md` says `sales@nmap.com`. Do you work there or in :yemen:  :-)

**Comment by sgeto** [comment]
Hehe I'm not affiliated with nmap/npcap at all. I forked their repo and this is just their old readme. I need to change it. It's far from perfect but I'm getting there.
I live in Yemen (GMT +3). You got that right. Didn't know GitHub had a flag for Yemen. lol

**Comment by gvanem** [comment]
Lot of Emojis here; the code is simply ` :yemen:`.

**Comment by sgeto** [comment]
You should try the offical Npcap first (I think my fork is currently only usable by me. Everything is still in an alpha stage). And let me know if that fixes the timestamp dilema. :norway:

**Comment by koeppea** [comment]
Hey folks,

may I remind you, that we have also a IRC channel for off-topic and als
on-topic discussions.....

Cheers Alex

**Comment by sgeto** [comment]
Thanks. But I'm often on my phone, I don't have access to IRC there...

**Comment by koeppea** [comment]
Had a look at the recent changes and how the builds on Travis went through. Looks better now. However, not yet tested.
Do I understand correctly, that GeoIP support is by default not enabled? 
What is the reasoning behind not enabling by default?

**Comment by sgeto** [comment]
Not too sure why I set it to off by default. I guess I think of it as something optional like lua or IPv6 (which should be on IMO anyways).
Personally, I always build with GeoIP support. I guess it would be nice to have it on by default if you ask me.

**Comment by koeppea** [comment]
Please set it to on by default.

**Comment by koeppea** [comment]
@sgeto if you would now rebase your branch over the latest **upstream/master** it's ready for merge.

**Comment by sgeto** [comment]
@koeppea 
sure. I want to clarify something first...

@gvanem 
Hi!

I decided to put my Lua PR on hold for a bit. Life's too short...

But I would still like to include your `geoip_demo.lua` as part of this PR. It's nice.
You said that if ettercap was built w/o WITH_GEOIP, this script fails to run, which makes sense.
My approach would be to simply not install `geoip_demo.lua` if ettercap was built without GeoIP support. Your idea is to convert all geoip_*() functions to empty stubs.
I am a bit skeptical about that. I also seem like an overkill.

1. Anyways have you done that already? Or could you do that and share a patch?
2. Should we use the one that prints timestamps?
3. Do you want to add a copyright notice to the top of the script?

**Comment by koeppea** [comment]
> I decided to put my Lua PR on hold for a bit. 

Do want to close the PR and when your branch is ready opening a new one? Or do you prefer keeping this one?

**Comment by sgeto** [comment]
@koeppea 
I guess I should close it for now...

**Comment by sgeto** [comment]
@koeppea is my branch up-to-date with master? I seriously lost track,

**Comment by koeppea** [comment]
Seem to be. GitHub can fast-forward which is a good indication that the pr is on top of master.

**Comment by koeppea** [comment]
Ready for merge?

**Comment by sgeto** [comment]
Okay, You can merge now. I was actually waiting on Gisle but I guess I do it in a separate PR.

**Comment by koeppea** [comment]
OK. I'm anyways a fan of unmixed PRs.

**Comment by koeppea** [comment]
Thanks

**Comment by gvanem** [comment]
@sgeto : What are you waiting for my input for? You know I stay far away from Cmake. So I have nothing to contribute in that respect. Please just add the `geoip_demo.lua`  script. The idea re. the empty `geoip_*()` stubs can be dropped AFAICS.

**Comment by sgeto** [comment]
Wish you gave me the green light before the merge...
I wasn't going to get you into cmake stuff. 
I just needed to know if you were fine with adding your script.

**Comment by koeppea** [comment]
Just raise another PR.

As I said, I like scoped PRs.

**Pull request merged**
