### PR TITLE
Lua

### PR DESCRIPTION
**Pull request by sgeto**
A few general improvements for lua bindings. See commits.

### CODE REVIEW

**Comment by eaescob** [comment]
Don't use the Lua implementation too much, is this tested?

**Comment by sgeto** [comment]
I didn't have the time to test it throughout. I tried a few and the result is mixed. Some work, others not so much, and others not at all.
I'm not sure though if this has more to do with my main OS than the bindings themselves. (I am mostly on Windows)

**Comment by koeppea** [comment]
I haven't ever worked with LUA scripts.
How to use them? I cannot tell what the PR does actually.

**Comment by gvanem** [comment]
I too tried Lua w/o knowing much about it. With `HAVE_EC_LUA`, `ettercap.exe -h` won't even do anything.
It just sits there. The call-stack from ProcessExplorer shows this:
```
...
ntdll.dll!NtWaitForSingleObject+0xc
KERNELBASE.dll!WaitForSingleObject+0x12
ettercap_c.dll!_pthread_mutex_lock+0x77
ettercap_c.dll!debug_msg+0x19
ettercap_c.dll!get_local_path+0x8f
ettercap_c.dll!ec_lua_print_info+0x22
ettercap.exe!__scrt_common_main_seh+0xf8
```

Hm?

**Comment by gvanem** [comment]
I switched to Lua 5.3. That works much better. Except it needed this patch to compile and link:
```diff
--- a/lua/ec_lua.c 2017-10-29 09:57:24
+++ b/lua/ec_lua.c 2017-12-29 10:53:35
@@ -304,18 +304,29 @@

 LUALIB_API int luaopen_ettercap_c(lua_State *L)
 {
+#if (LUA_VERSION_NUM >= 502)
+  lua_newtable(L);
+  luaL_setfuncs(L, ec_lua_lib, 0);
+  lua_setglobal(L, ETTERCAP_C_API_LUA_MODULE);
+#else
   luaL_register(L, ETTERCAP_C_API_LUA_MODULE, ec_lua_lib);
+#endif
   return 1;
 }
```

**Comment by sgeto** [comment]
This PR just fixes a few _build related_ issues. 
It removes the duplicate entry of `inject_http.lua`. You can reproduce the problem when running `make install/uninstall` (there will be a warning).

The other fix is an improvement in portability. Not every compiler uses the `-fPIC` flag. I think it's therefore much better to use a the cmake property `POSITION_INDEPENDENT_CODE`. If done so, cmake will set the proper PIC flags based on the compiler used for building ettercap.

**Comment by sgeto** [comment]
@gvanem
Were you having issues with loading lua scripts or issues with building the bindings in general?

**Comment by koeppea** [comment]
@sgeto can you verify @gvanem hint. Does it make sense in your eyes. 
As I said. I've not that much experience with LUA at all.

**Comment by gvanem** [comment]
> Were you having issues with loading lua scripts or issues with building the bindings in general?

None of the above. I now have problem with e.g. `tcp_session_demo.lua`, which works until this:
```
EC_LUA ec_lua_dispatch_hooked_packet Failed. Error 2: ./share/lua/ettercap.lua:41: 
bad argument #4 to 'format' (number expected, got function)
```
As I wrote, I don't know LUA that well. So I fail to see how/why Lua is bitching about arguments given to `log()`.  AFAICS, this is the C-function `l_log()` in `ec_lua.c`.

The error-message in this language are terrible. I would be nice with a call-stack to show how the code landed at that place. Or maybe it's possible to verify all the scripts with `luac` before running them in ettercap?

**Comment by sgeto** [comment]
@gvanem I share your frustration. I've spent a lot of time figuring the problem you've mentioned out and I still don't have a complete answer.

The bindings were written by @justfalter and @sussurro and in their defense, it's marked it as experimental. I think "incomplete" is probably a better word for this... mess. (Let's hope this message reaches them and sparks their interest to continue/finalize it).

I will share some thoughts/notes/suggestions now. Feel free to correct me or give feedback of any kind.

As far as I can tell, you're having problems initializing the Lua bindings altogether. Your error occurs in ettercap.lua, which is loaded before any custom lua script. You're not even getting past it that, correct? 

I don't have this issue (anymore). The binding initializes (more or less) fine on my machine. You should also know that, as far as I can tell, errors in scripts after the stage that is currently failing for you includes human-readable error messages.
I remember struggling with these absolutely not helpful error codes a while ago. That was more than a year ago so I don't exactly recall how I got passed them.

Nonetheless, I'm almost certain that it has to do with the way you're linking the Lua stuff with libettercap.dll (or ettercap_c.dll). Correct me if I am wrong.

Simply put: Don't add the Lua stuff (*.c files) as part of libettercap's sources. It should be built as a separate (static) library and, at the very end, linked with libettercap. Almost like a plugin.
The original developers didn't leave any notes as to why, so I am guessing the reason for this is that the binding must be exposed to the ettercap's API as a whole. It needs to import them...

This, however, will only get you a bit further. The binding only has access to those of functions that libettercap exports. That's why some script work and others don't.
I really think that this is a problem with the ettercap API and not the bindings.
I mentioned before that I think the way libettercap exports the functions needed by its applications, plugins and now Lua bindings is very sloppy. This is even worse on windows, where only things properly decorated are exported/imported. 

It is not enough to simply include `ec.h` to gain access to the entire API. Many files such as missing/memmem.h must be manually included.

Having said that, and having experienced how much trouble this can cause, it becomes clear that the problems you will be facing after fixing your current problem are libettercap related issues. Not so much Lua related issues.

Personally, I think that finding a solution for the how exports are handled is the most important issue at hand. After merging or closing this, I will concentrate most of my involvement in fixing that.

By the way: Thanks for the patch. Adding compatibility with Lua 5.2+ is very useful and important. I will add the patch as part of this PR. I also used it as starting point for the (similarly shitty) Lua bindings of my libnet fork.

**Comment by sgeto** [comment]
@LocutusOfBorg I see that you added the PIC change from here to your library fix PR.
I hate to cause merge conflicts, that's why I first thought to remove it from this PR. 
But the problem is that I could use this change as soon as possible.
I would like to keep them here if it's okay because this PR is expected to be merged much sooner than your library fix.

**Comment by sgeto** [comment]
> I switched to Lua 5.3. That works much better. Except it needed this patch to compile and link

Seems like I don't need it. It seems to work without it...

**Comment by gvanem** [comment]
@sgeto I'm not sure what to answer to all of the above. But my initial problem of:
```
EC_LUA ec_lua_dispatch_hooked_packet Failed. Error 2: ./share/lua/ettercap.lua:41: 
bad argument #4 to 'format' (number expected, got function)
```

I managed to fix after learning a bit more Lua (and experimenting with it in [wsock_trace](https://github.com/gvanem/wsock-trace)). Here is the patch for that:
```diff
--- a/src/lua/share/scripts/tcp_session_demo.lua 2015-02-09 13:49:06
+++ b/lua/share/scripts/tcp_session_demo.lua 2017-12-30 14:19:27
@@ -239,11 +239,16 @@

   if dir == 0 then
     handle_request(session_data, packet_object)
+    dir_str = "C->S"
   else
     handle_response(session_data, packet_object)
+    dir_str = "S->C"
   end

-  -- ettercap.log("tcp_session_demo: %d %s:%d -> %s:%d - state: %s\n", dir, src_ip, src_port,
-  --                  dst_ip, dst_port, tostring(session_data.http_state))
+  p = packet_object
+
+  ettercap.log("tcp_session_demo: %s %s:%d -> %s:%d - state: %s\n", dir_str,
+               packet.src_ip(p), packet.src_port(p),
+               packet.dst_ip(p), packet.dst_port(p), tostring(session_data.http_state))

 end
```
Could probably write that as `, src_ip(), src_port(),..`.

**Comment by sgeto** [comment]
> I'm not sure what to answer to all of the above

Don't worry. I'll get to it in more detail soon.

> EC_LUA ec_lua_dispatch_hooked_packet Failed. Error 2: ./share/lua/ettercap.lua:41: 
> bad argument #4 to 'format' (number expected, got function)

It's so strange that can't reproduce this error/problem.
I have issues, but this isn't one of them.
Can you tell me a bit more about your setup? You know, your compiler, CFLAGS, OS and version and stuff? And are you building with current master?

**Comment by LocutusOfBorg** [comment]
@sgeto please go ahead with the fixes, I can fixup the conflicts later (or even rebase and discard my cherry-pick)

**Comment by sgeto** [comment]
@gvanem
Can you explain these errors I keep getting? I really hope you've seen this before.

```
EC_LUA ec_lua_dispatch_hooked_packet Failed. Error 2: C:/msys64/mingw64/share/ettercap/lua/core/packet.lua:26: cannot resolve symbol 'ip_addr_ntoa': The specified procedure could not be found.

EC_LUA ec_lua_dispatch_hooked_packet Failed. Error 2: ...s64/mingw64/share/ettercap/lua/scripts/get_imap_demo.lua:35: cannot resolve symbol 'ntohs': The specified procedure could not be found.

EC_LUA ec_lua_dispatch_hooked_packet Failed. Error 2: .../mingw64/share/ettercap/lua/scripts/inject_http_demo.lua:288: cannot resolve symbol 'tcp_create_ident': The specified procedure could not be found.
```

The first one is from your `geoip_demo.lua`. As I explained, I'm not sure where the problem originates from or where to start looking.

**Comment by justfalter** [comment]
> The bindings were written by @justfalter and @sussurro and in their defense, it's marked it as experimental. I think "incomplete" is probably a better word for this... mess. (Let's hope this message reaches them and sparks their interest to continue/finalize it).

I wish I could help out, but the terms of my employment don't really allow me to contribute to open source stuff, anymore. As I recall, the stuff I put together for the Lua bindings was just enough to get the environment working, leveraging the existing Ettercap C api.

One thing I will point out about the stuff I did: it required the Luajit library (http://luajit.org/) not plain old Lua (http://www.lua.org/). Rather than writing (in C) Lua bindings for all of the Ettercap C api stuff, we were using Luajit's FFI library (http://luajit.org/ext_ffi.html) to bind at runtime. Take a look at https://github.com/Ettercap/ettercap/blob/d398cbad70bc0f893bf6a095568cd5dfcf19ee2d/src/lua/share/core/packet.lua and https://github.com/Ettercap/ettercap/blob/d398cbad70bc0f893bf6a095568cd5dfcf19ee2d/src/lua/share/core/ettercap.lua to see how this is done. 

As I recall, there was no need to point the Ettercap build process at an external Lua library - it would use a bundled version of luajit.

**Comment by gvanem** [comment]
@sgeto  cannot resolve symbol 'tcp_create_ident': 

I cannot explain this just like that. Check if those are really exported from `ettercap_c.dll`:
```
pedump ettercap_c.dll | grep tcp_create_ident
dumpbin -exports ettercap_c.dll | grep  tcp_create_ident
```
(or some other MinGW tool I cannot remember).

And that `ettercap_c.dll` is really found in `package.cpath` or `LUA_CPATH`. Is it found by other scripts?

**Comment by justfalter** [comment]
Are you building using luajit or lua? If you’re using regular lua, that
would very likely be the cause of your issues. luajit provides ffi, which
is used to load the library. If you’re using regular lua, it doesn’t have
ffi, and therefore cannot load the library.

**Comment by sgeto** [comment]
This is tiring and frustrating. Seriously.

> Check if those are really exported from ettercap_c.dll

They are exported. I named my DLL `libettercap.dll` as opposed to `ettercap_c.dll`. That's not a problem, right?

@justfalter thanks for clarifying and helping out still. Yes, I am using luajit.

**Comment by gvanem** [comment]
> That's not a problem, right?

Well a `require("ettercap_c")` in `ettercap.lua` tells me it's a huge problem.

**Comment by sgeto** [comment]
`libettercap` is the default libname set by cmake. Renaming it to `ettercap_c` just for lua bindings seems like an overkill. Besides, manally renaming all instaces of `ettercap_c` didn't do the trick for me either.
I'd like to attach a more useful debugger. Can you share your makefile?

**Comment by gvanem** [comment]
>  Can you share your makefile?

In you mail, but it's complicated and really only for me and my setup.

**Comment by sgeto** [comment]
Thanks. I'll check it out.

**Pull request closed without merging**
