### PR TITLE
OpenBSD build fixes

### PR DESCRIPTION
**Pull request by koeppea**
On OpenBSD, some things need to get adjusted to get Ettercap built on OpenBSD.

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
Looks good to me, modulo trying to understand if the two patches are still needed now!

**Comment by koeppea** [comment]
Rebased over latest master.
Well these changes enables Ettercap being built on OpenBSD. However OpenBSD has some strange versions of header files and library versions.

**Comment by LocutusOfBorg** [comment]
So, we still need the patches? can we upstream them to libnet maintainers?

**Comment by koeppea** [comment]
We can try. Keep it out for the sub release.

**Comment by LocutusOfBorg** [comment]
@koeppea rebase and merge?

**Comment by koeppea** [comment]
Yes I think we're can merge however I guess it should be rebased first

**Comment by LocutusOfBorg** [comment]
rebased and merged!

**Pull request merged**
