### PR TITLE
Update changelog for 0.8.2

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
After 8 CVE fixed I think we should release something ;) (gentoo is asking for a release).

Now the problematic part:
how will it be called? :)

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
Updated the Changelog with the new release name

**Comment by koeppea** [comment]
Didn't we wanted to release 0.8.2? Can I take over anything necessary?

**Comment by LocutusOfBorg** [comment]
I'm wondering about #666 :)

**Comment by koeppea** [comment]
Well it came in later.
With this release we wanted to reflect the security related vulnerabilities.
I think this is more urgent.
Issues will continue to come in for sure. We can address them in further releases.

**Comment by LocutusOfBorg** [comment]
lets wait for travis and release then!

**Pull request merged**
