### PR TITLE
Fix issue #782

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by koeppea** [comment]
Doesn't this PR just circumvent the actual issue?
From my point of view, GBL_PROGRAM is the issue, isn't it?

```
The program being debugged has been started already.
Start it from the beginning? (y or n) y

Starting program: /home/koeppea/tmp/ettercap/bin/etterfilter ../Downloads/crash.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

etterfilter 0.8.2 copyright 2001-2015 Ettercap Development Team


 14 protocol tables loaded:
	DECODED DATA udp tcp esp gre icmp ipv6 ip arp wifi fddi tr eth 

 13 constants loaded:
	VRRP OSPF GRE UDP TCP ESP ICMP6 ICMP PPTP PPPOE IP6 IP ARP 

 Parsing source file '../Downloads/crash.txt'  done.



BUG at [/home/koeppea/dev/ettercap/utils/etterfilter/ef_compiler.c:compile_tree:242]

 tree_root == NULL 


Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b6ddd6 in clean_exit (errcode=-666) at /home/koeppea/dev/ettercap/src/ec_exit.c:38
38	   INSTANT_USER_MSG("\nTerminating %s...\n", GBL_PROGRAM);
(gdb) print GBL_PROGRAM
There is no member named env.
(gdb) l
33	
34	void clean_exit(int errcode)
35	{
36	   DEBUG_MSG("clean_exit: %d", errcode);
37	  
38	   INSTANT_USER_MSG("\nTerminating %s...\n", GBL_PROGRAM);
39	
40	#ifdef HAVE_EC_LUA
41	   /* Cleanup lua */
42	   ec_lua_fini();
(gdb)
```

Seems to be overlaying the pre-processor definition **GBL_PROGRAM**:
```
$ grep GBL_PROGRAM * -RI
include/ec_globals.h:#define GBL_PROGRAM        (GBL_ENV->name)
include/ef.h:#define GBL_PROGRAM "etterfilter"
```

I know it's very hard to harmonize the utils with the library, but this seem to be a side effect of it.

**Comment by koeppea** [comment]
@LocutusOfBorg any opinion on my last comment?

**Comment by koeppea** [comment]
What about using EF_GBL_PROGRAM in **etterfilter** instread?

**Comment by LocutusOfBorg** [comment]
I don't get sorry :)
my fix-library has EF_GBL_PROGRAM, but this pr is intended for the actual main (for people using the latest stable).
Yes, eventually will become EF_GBL_PROGRAM, but right now the priority is to fix CVE against stable with a patch mergeable in stable.

**Comment by koeppea** [comment]
ACK.
I understood now that the issue doesn't lie in the etterfilter sources rather than lib_ettercap, hence it cannot be addressed easily by adjusting the etterfilter sources.
I agree that this approach is the least effort to address this issue.
This PR is ready to go for me :+1:

**Pull request merged**
