### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by koeppea**
Several changed dependencies need to be treated to make Travis happy again.

### CODE REVIEW

**Comment by sgeto** [comment]
Can you try my modified `FindGTK3.cmake` module?
[FindGTK3.zip](https://github.com/Ettercap/ettercap/files/3618645/FindGTK3.zip)

The HarfBuzz stuff is integrated into FindGTK3, so make sure to remove the entries in `EttercapLibCheck.cmake` - or not, whatever works best I guess. 😅 

I think that the `FindHarfBuzz.cmake` module you added should already be part (newer) cmake versions. So maybe you can check if you already have that file and leave the local copy out.
See [commit f0c9e72e](https://gitlab.kitware.com/cmake/cmake/commit/f0c9e72ee152e1e4acda8efeed9c2e3e408b2658#58185a7528d74478217625e6c21fe5e83e2f9302)

**Comment by koeppea** [comment]
Thanks @sgeto, will do.

**Comment by koeppea** [comment]
Alright. Done. Let see if Travis becomes happy.

**Comment by koeppea** [comment]
Hi @sgeto,

good news, the _FindGTK3.cmake_ you've provided detects successfully harbuzz on Linux.
bad new, it isn't also not able to find Harfbuzz on MacOSX --> Travis failures.

Do you know where this cmake file originated from? Maybe we can query the author.

**Comment by sgeto** [comment]
> Do you know where this cmake file originated from? Maybe we can query the author.

Sorry no. Last time I checked `FindGTK3.cmake` was passed around a few times and then abandoned.

Correct me if I'm wrong: The reason cmake is unable to find the header is because it's in a unusual directory, right? According to #966 `hb.h` is  in `$PREFIX/usr/include/harfbuzz/hb.h`?

Maybe we can bring our local `FindHarfBuzz.cmake` back and tweak `find_path()` to additionally look in that directory?

[FindHARFBUZZ.zip](https://github.com/Ettercap/ettercap/files/3634399/FindHARFBUZZ.zip)

Can you try this?

**Comment by sgeto** [comment]
I think [this line](https://travis-ci.org/Ettercap/ettercap/jobs/587967471#L2257) means that cmake found hb.h but not the library.
Another thing we could try is to set the environment variable `HARFBUZZ_DIR` instead of `HARFBUZZ_ROOT_DIR` in `travis.yml`. The find module seems to somewhat honor this variable.

I going to assume now that the library is located somewhere in `/usr/lib` and attach an updated 
`FindHarfBuzz.cmake` that is setup to check there as well. Fingers crossed!

[FindHARFBUZZ.zip](https://github.com/Ettercap/ettercap/files/3639450/FindHARFBUZZ.zip)

**Comment by sgeto** [comment]
Whoa, frustrating...
I got more:
I found this module that uses the pkgconfig to locate harfbuzz.
[FindHarfBuzz.zip](https://github.com/Ettercap/ettercap/files/3639896/FindHarfBuzz.zip)

**Comment by koeppea** [comment]
Seems I've to grab a real Mac to better troubleshoot....

**Comment by sgeto** [comment]
Good idea.

**Comment by koeppea** [comment]
Well your last version of the file seem to work.
Just CMake Linter is failing. Just confirmed the style and then Travis should be happy again.
Before mergin I'll of course fixup all the commits.

**Comment by koeppea** [comment]
Should be good to merge now. @sgeto What do you think?

**Comment by sgeto** [comment]
I think the stuff in `EttercapLibCheck.cmake` is redundant. We should leave it out.
I am also not very happy with having introduce yet another dependency (pkg-config) to all of ettercap just because of macos. Pkg-config was only needed when building the tests, meaning that people didn't need to have to build ettercap.
Personally, I think the fact that cmake's own `FindHARFBUZZ.cmake` module is unable to locate harfbuzz is a bug and that should be addressed upstream. I guess it will be at some point question only is when.
If possible it would be nice if we could fall back to pkg-config stuff or limit it to macos only.

**Comment by koeppea** [comment]
I'd don't think thats a too big issue, since this is only relevant if the OS is MAC.
However I don't think that the Stuff in `EttercapLibCheck.cmake` can't be omitted since `FindGTK3.cmake` alone cannot find it, at least not on MAC. However I can try if you want.

Regarding CMake upstream: I've already opened a issue for the CMake Folks for the same issue, but referencing to `FindGTK3.cmake`. They said that they do not provide that. So I'm pretty sure `FindHARFBUZZ.cmake` is also not officially from CMake.

**Comment by koeppea** [comment]
@sgeto Any further comment? Are we good to merge?
This way I'll be able to rebase the other pending pull requests.

**Comment by koeppea** [comment]
Hey @sgeto have you had a chance to look over this PR?

**Comment by koeppea** [comment]
Hi @sgeto You've been busy last weeks isn't it? Could you please do the review of this PR as it's blocking all remaining PRs from getting Travis build successful.
Thanks.

**Comment by koeppea** [comment]
Since @sgeto seems to be unresponsive ATM, I hope you @LocutusOfBorg can take over reviewing this PR.

**Comment by sgeto** [comment]
Sorry. I am going through a rough time. This PR is of course okay.
Again sorry for the huge delay.

You may merge it now. Or I'll if GitHub won't let you...

**Comment by koeppea** [comment]
Thanks Ali

**Pull request merged**
