### PR TITLE
Update curl to 7.42.1

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by koeppea** [comment]
De ja vu?

**Comment by LocutusOfBorg** [comment]
this is a .1, due to some CVEs :)

**Comment by koeppea** [comment]
Ah OK. Just wasn't sure.

**Comment by koeppea** [comment]
Howerver,  tested and works as well. Maybe you can manage the extra "merge" commit.

**Comment by koeppea** [comment]
I'm not sure about the actual content of the commit. If it's really just merging the current master into this branch, I can also do it for you. I should still have permissions on your fork.

**Comment by LocutusOfBorg** [comment]
it was a mistake, I'll fix it when I reach my pc, sorry for that :)

**Comment by LocutusOfBorg** [comment]
should be fine now :)

**Pull request merged**
