### PR TITLE
Fix for issue #836

### PR DESCRIPTION
**Pull request by eaescob**
This should take care of #836 if I am not mistaken

### CODE REVIEW

**Comment by mnciitbhu** [comment]
I think the condition `if (!poison_oneway)` should be before [line 341](https://github.com/Ettercap/ettercap/pull/844/files#diff-2327c4ec66787ee72ec1538e695cf337R341).

**Comment by mnciitbhu** [comment]
The variable name is `poison_oneway` and not `oneway_poison`.

**Comment by eaescob** [comment]
Sorry! Shouldn't been doing other things. Fixed typo, compiled and tested.

**Comment by koeppea** [comment]
Alright. Would you mind squashing you commits. Then I'd merge.

**Comment by eaescob** [comment]
Squashing and merging

**Pull request merged**
