### PR TITLE
Fix OSX warning

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by koeppea** [comment]
How is the `struct timeval` defined on a MacOSX?

**Comment by LocutusOfBorg** [comment]
I don't know, maybe this way
http://macosx.com/threads/timeval-from-sys-resource-h-not-defined.12114/

anyway seems that also linux defines it in the same way, so I unified everything, lets wait for travis

**Comment by koeppea** [comment]
Ah now I see where it's coming from... :smile:

**Comment by LocutusOfBorg** [comment]
Nope, seems to be not working
https://travis-ci.org/Ettercap/ettercap/jobs/53163318

they are different, rebased and updated, lets see travis

**Comment by koeppea** [comment]
Rebased over current Master

**Comment by koeppea** [comment]
Ups. race condition

**Comment by koeppea** [comment]
Hui. Wasn't finished.
Well nevermind. I'll create another pull request for that.

**Comment by LocutusOfBorg** [comment]
yep, I prefer to merge because the delta with my fix-library branch becomes painful to maintain :)

**Pull request merged**
