### PR TITLE
update port redirect commands for MacOS X

### PR DESCRIPTION
**Pull request by koeppea**
Another try to get port redirection working on current MacOSX

### CODE REVIEW

**Comment by eaescob** [comment]
does it work?

**Comment by koeppea** [comment]
Can't confirm. It works on FreeBSD. Lack of testing equipment. Do you own a Mac running Yosemite?

**Comment by eaescob** [comment]
i do, i can try this

**Comment by depulsor** [comment]
Does not work for me. Victim's PC has no connection to the internet after activating sslstrip. No errors
Mac with 10.11.4

**Comment by koeppea** [comment]
What do you mean by "after activating sslstrip"?
Do you mean the plugin sslstrip or the standalone binary sslstrip?

Have you just modified the commands as done in this pull request or have you merged this pull request and recompiled it?

What is the output when you start ettercap?
Can you please paste the output of `pf -sn` and `lsof -i` after you've started ettercap?
I'd also be interested in the ettercap-debug file.

**Comment by koeppea** [comment]
Meanwhile I've been able to grab a MacBook from our test devices :-)

I've built ettercap from github and enabled the redir_command_(on|off) from the FreeBSD section.
From my point of view it does what it's supposed to do. 

```
$ sudo pfctl -sn
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
rdr pass on en0 inet proto tcp from any to any port = 992 -> 127.0.0.1 port 59263
rdr pass on en0 inet6 proto tcp from any to any port = 992 -> ::1 port 59263
rdr pass on en0 inet proto tcp from any to any port = 465 -> 127.0.0.1 port 59264
rdr pass on en0 inet6 proto tcp from any to any port = 465 -> ::1 port 59264
rdr pass on en0 inet proto tcp from any to any port = 995 -> 127.0.0.1 port 59265
rdr pass on en0 inet6 proto tcp from any to any port = 995 -> ::1 port 59265
rdr pass on en0 inet proto tcp from any to any port = 563 -> 127.0.0.1 port 59266
rdr pass on en0 inet6 proto tcp from any to any port = 563 -> ::1 port 59266
rdr pass on en0 inet proto tcp from any to any port = 636 -> 127.0.0.1 port 59267
rdr pass on en0 inet6 proto tcp from any to any port = 636 -> ::1 port 59267
rdr pass on en0 inet proto tcp from any to any port = 994 -> 127.0.0.1 port 59268
rdr pass on en0 inet6 proto tcp from any to any port = 994 -> ::1 port 59268
rdr pass on en0 inet proto tcp from any to any port = 993 -> 127.0.0.1 port 59269
rdr pass on en0 inet6 proto tcp from any to any port = 993 -> ::1 port 59269
rdr pass on en0 inet proto tcp from any to any port = 8080 -> 127.0.0.1 port 59270
rdr pass on en0 inet6 proto tcp from any to any port = 8080 -> ::1 port 59270
rdr pass on en0 inet proto tcp from any to any port = 443 -> 127.0.0.1 port 59271
rdr pass on en0 inet6 proto tcp from any to any port = 443 -> ::1 port 59271
rdr pass on en0 inet proto tcp from any to any port = 990 -> 127.0.0.1 port 59272
rdr pass on en0 inet6 proto tcp from any to any port = 990 -> ::1 port 59272
$
```

```
$ sudo lsof -i -sTCP:LISTEN | grep ettercap
ettercap  13336           root   15u  IPv4 0x501cac1dd5c5f19d      0t0  RAW *:*
ettercap  13336           root   16u  IPv6 0x501cac1dd5c5f405      0t0  RAW *:*
ettercap  13336           root   17u  IPv4 0x501cac1dd694b13d      0t0  TCP *:59263 (LISTEN)
ettercap  13336           root   18u  IPv6 0x501cac1dd2b6035d      0t0  TCP *:59263 (LISTEN)
ettercap  13336           root   19u  IPv4 0x501cac1dd5a6751d      0t0  TCP *:59264 (LISTEN)
ettercap  13336           root   20u  IPv6 0x501cac1dd8cc033d      0t0  TCP *:59264 (LISTEN)
ettercap  13336           root   21u  IPv4 0x501cac1dd2b6751d      0t0  TCP *:59265 (LISTEN)
ettercap  13336           root   22u  IPv6 0x501cac1dd2b6137d      0t0  TCP *:59265 (LISTEN)
ettercap  13336           root   23u  IPv4 0x501cac1dd9195a35      0t0  TCP *:59266 (LISTEN)
ettercap  13336           root   24u  IPv6 0x501cac1dd8cbdd9d      0t0  TCP *:59266 (LISTEN)
ettercap  13336           root   25u  IPv4 0x501cac1dd5b36a35      0t0  TCP *:59267 (LISTEN)
ettercap  13336           root   26u  IPv6 0x501cac1dd5b6b31d      0t0  TCP *:59267 (LISTEN)
ettercap  13336           root   27u  IPv4 0x501cac1dd5a67e15      0t0  TCP *:59268 (LISTEN)
ettercap  13336           root   28u  IPv6 0x501cac1dd5b6c89d      0t0  TCP *:59268 (LISTEN)
ettercap  13336           root   29u  IPv4 0x501cac1dd5a66c25      0t0  TCP *:59269 (LISTEN)
ettercap  13336           root   30u  IPv6 0x501cac1dd2b60e1d      0t0  TCP *:59269 (LISTEN)
ettercap  13336           root   31u  IPv4 0x501cac1dd670113d      0t0  TCP *:59270 (LISTEN)
ettercap  13336           root   32u  IPv6 0x501cac1dd2b5f33d      0t0  TCP *:59270 (LISTEN)
ettercap  13336           root   33u  IPv4 0x501cac1dd770a70d      0t0  TCP *:59271 (LISTEN)
ettercap  13336           root   34u  IPv6 0x501cac1dd2b5f89d      0t0  TCP *:59271 (LISTEN)
ettercap  13336           root   35u  IPv4 0x501cac1dd670870d      0t0  TCP *:59272 (LISTEN)
ettercap  13336           root   36u  IPv6 0x501cac1dd2b5e31d      0t0  TCP *:59272 (LISTEN)
$ 
```
However a functional test ist currently still outstanding.
But up to now, it looks to me that the redid_command_(on|off) of the section "FreeBSD" do work for MacOSX also.

**Comment by eaescob** [comment]
Excellent! Let me see if I can take it for a spin this week

**Comment by koeppea** [comment]
Obviously `pfctl -Psn` isn't supported on Mac OS X. This leads to a improper removal of NAT rules resulting in a complete flush of the NAT rules.
This does basically only have an effect if the plugin sslstrip is activated and again deactivated.

**Pull request merged**
