### PR TITLE
Fix issue #865 - Regex compilation prevents sslstrip plugin to load

### PR DESCRIPTION
**Pull request by koeppea**
This PR fixes an "invalid range end" regex issue.
In addition the error message is annotated with the string representation of the acutal error.

### CODE REVIEW

**Comment by sgeto** [comment]
Could you please rename your PRs to something more... catchy?

**Comment by koeppea** [comment]
better?

**Comment by sgeto** [comment]
Pretty much.

**Comment by koeppea** [comment]
@eaescob ready to merge from my side. Are you also happy?

**Comment by eaescob** [comment]
👍 thanks guys!

**Pull request merged**
