### PR TITLE
Add displaying the payload length in the packet header output

### PR DESCRIPTION
**Pull request by mmaxs**
This is an proposal accompanying to pull request #656, which can be applied independently.

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
nack sorry
```
/home/travis/build/Ettercap/ettercap/src/interfaces/text/ec_text_display.c: In function ‘display_headers’:

/home/travis/build/Ettercap/ettercap/src/interfaces/text/ec_text_display.c:124:57: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 9 has type ‘size_t’ [-Wformat]
```

**Comment by LocutusOfBorg** [comment]
don't know... maybe u_int?

**Comment by LocutusOfBorg** [comment]
can you please also fix the two typos?
```
       * this is that bufffer and it is malloced by tcp or udp dissector.
      u_char *inject;         /* the fuffer used for injection */
```

thanks a lot! :)

**Comment by mmaxs** [comment]
> don't know... maybe u_int?
Me too, I've just amended so that travis must to be satisfied. By guess, as far as I don't see this warning on gcc Red Hat 4.8.3-7 while travis uses Ubuntu/Linaro 4.6.3-1ubuntu5

**Comment by koeppea** [comment]
Are you building build type Debug? Otherwise you don't see compiler warnings.

**Comment by koeppea** [comment]
Now I'm also not getting the warning anymore. Travis seem to be happy as well.

**Comment by eaescob** [comment]
Merge?

**Comment by mmaxs** [comment]
> Are you building build type Debug? Otherwise you don't see compiler warnings.

There is a ton of cluttered custom warnings with a debug build. I am compiling a release build with changed flags. It fails on every unqualified warning.
```
-set(CMAKE_C_FLAGS_RELEASE "-O2 -w -D_FORTIFY_SOURCE=2" CACHE STRING "" FORCE)
+set(CMAKE_C_FLAGS_RELEASE "-O2 -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wformat-security -Wredundant-decls  -Wno-pointer-sign -Wno-unused-result -Wno-empty-body -Wno-unused-variable -Wno-unused-parameter  -Werror" CACHE STRING "" FORCE)
```

**Comment by LocutusOfBorg** [comment]
thanks!

**Pull request merged**
