### PR TITLE
Fix 774: reliable reflect spoofed DNS reply on same interface

### PR DESCRIPTION
**Pull request by koeppea**
This pull request addresses issue #774 as the send function does not properly take the dual interface situation into account in bridged sniffing mode.

### CODE REVIEW

**Comment by koeppea** [comment]
Hi @LocutusOfBorg too fast.
I intended to prepare a alternative approach which in my point of view may be more elegant:
in _send_m?dns_reply()_:
 1. use libnet to build the protocol stack for the DNS reply
 2. create ettercap packet_object 
 3. use the sniffing method's forwarding function

What do you think how to approach this since this PR is now merged already?

**Comment by koeppea** [comment]
@LocutusOfBorg do you know why some of the Travis builts failed? Mainly MacOSX.

**Comment by LocutusOfBorg** [comment]
Do another pr :) yes there has been a Macosx regression that made builds fail.
I honestly don't care too much since I have no real hw here

**Comment by koeppea** [comment]
Nevermind. the outlined approach doesn't make it more elegant, since building of the link-layer header is dependent on the outgoing interface. So this approach would just lead to additional processing.
So merging this one was correct.

**Comment by LocutusOfBorg** [comment]
thanks :) it looked really nice and clean to me!

**Comment by koeppea** [comment]
> since I have no real hw here

I have meanwhile a MacOS device available. I'll try to reproduce the Travis failure.

**Pull request merged**
