### PR TITLE
Fixed a compile warning

### PR DESCRIPTION
**Pull request by sgeto**
I think I just fixed the last compile warning.

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

If so, how about compiling on travis with `-Werror` from now on?

### CODE REVIEW

**Comment by koeppea** [comment]
Great.

I also spotted this one :-)

I don’t think we’d error on warnings. Some could sneak in from dependent libraries. We don’t have control over these. Current example when building on Debian: lex. I recall something like yy_parse or similar.

**Comment by sgeto** [comment]
> Current example when building on Debian: lex. I recall something like yy_parse or similar.

I saw that too. Turns out that this a bug in flex. It was fixed in newer versions

**Comment by koeppea** [comment]
Ok but my opinion is that we shouldn’t make our Travis builts relying on that.

**Comment by sgeto** [comment]
fine

**Comment by koeppea** [comment]
Merged thanks.

**Pull request merged**
