### PR TITLE
Alternative approach to fix #937

### LINKED ISSUE #937: Build failure in ec_stdint.h/wdg.c on Alpine with GCC 8.3
I have been attempting to build ettercap at commit ffeaac725d31f10b270cd3ece14e5a7b83a1f1ff on Alpine but have experienced the following issue:

```
# make
Scanning dependencies of target ec_interfaces
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text.c.o
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_conn.c.o
[  2%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_display.c.o
[  2%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_plugin.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_profile.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/daemon/ec_daemon.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg.c.o
In file included from /ettercap/e/src/interfaces/curses/widgets/wdg.h:21,
                 from /ettercap/e/src/interfaces/curses/widgets/wdg.c:22:
/ettercap/e/include/ec_stdint.h:37:10: error: unknown type name 'u_int8_t'
  typedef u_int8_t   u_int8;
          ^~~~~~~~
<snip>

In file included from /ettercap/e/src/interfaces/curses/widgets/wdg.c:22:
/ettercap/e/src/interfaces/curses/widgets/wdg.h:161:4: error: unknown type name 'u_char'
    u_char screen_color;

<output truncated>
```

I do not experience the same issue on Ubuntu 18.04.

However, upon further investigation, it appears that neither `ec_stdint.h` or `wdg.h` explicitly import `sys/types.h` for Linux (`wdg.h` does for Darwin) which is where these types are defined. 

On Ubuntu 18.04, it appears that `sys/types.h` is being implicitly imported within `wdg.h` when it imports `stdlib.h`. I.e.

```bash
$ echo "#include <stdlib.h>" | gcc -E - | grep -e "\(u_int8_t\)\|\(u_char\)"
typedef unsigned char __u_char;
typedef __u_char u_char;
typedef unsigned int u_int8_t __attribute__ ((__mode__ (__QI__)));
```

However, on Alpine this is not the case. I did not trace the imports to see the difference.

It appears there are two possible solutions, the first is to tweak `ec_stdint.h` to unconditionally include `sys/types.h` on Linux (perhaps for other OS'es as well?). That is, by adding:

```C
#if defined(OS_LINUX)
        #include <sys/types.h>
#endif
```

Alternatively, `wdg.h` can be updated as follows:
```diff
--- a/src/interfaces/curses/widgets/wdg.h
+++ b/src/interfaces/curses/widgets/wdg.h
@@ -14,7 +14,7 @@
    #include <windows.h>
 #endif
 
-#ifdef OS_DARWIN
+#if defined(OS_DARWIN) || defined(OS_LINUX)
    #include <sys/types.h>
 #endif
```

I am inclined to think the first is the better solution, however, the second appears to be more aligned with the existing code base. If needed, I can submit a PR.

### PR DESCRIPTION
**Pull request by koeppea**
Following the suggestion by @sgeto.
Could you give this pull request a try? See our [Wiki](https://github.com/Ettercap/ettercap/wiki/git-config#guidelines-how-to-contribute-to-the-project) how to fetch pull requests as dedicated branches.
The issue with the `u_char` may require a special treatment. But let's see how far we get with this?

### CODE REVIEW

**Comment by koeppea** [comment]
I mean: @kazkansouh: Could you give this pull request a try please?

**Comment by kazkansouh** [comment]
Thanks for this PR. Yep it fails on `u_char`.

```
# make
Scanning dependencies of target ec_interfaces
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text.c.o
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_conn.c.o
[  2%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_display.c.o
[  2%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_plugin.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_profile.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/daemon/ec_daemon.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg.c.o
In file included from /ettercap/src/interfaces/curses/widgets/wdg.c:22:
/ettercap/src/interfaces/curses/widgets/wdg.h:161:4: error: unknown type name 'u_char'
    u_char screen_color;
    ^~~~~~
```

**Comment by kazkansouh** [comment]
Looking at wdg.c, `u_char` is only used for interfacing with [color_pair](https://linux.die.net/man/3/color_pair) functions which use `short`. So at least in this case, it could be removed.

**Comment by sgeto** [comment]
u_char is also in ec_main.c (in the easter egg at the very bottom). You
could also just manually define it in ec_stdint.h and call it a day.

**Comment by kazkansouh** [comment]
> You could also just manually define it in ec_stdint.h and call it a day.

Thats true, but if going down that route would it not be cleaner to import `sys/types.h` in `ec_stdint.h` than mirroring its definitions? Its already imported under certain conditions in `ec_stdint.h`. I.e.

```C
#if defined HAVE_STDINT_H && !defined OS_SOLARIS
	#include <stdint.h>
#elif !defined OS_SOLARIS
	#include <sys/types.h>
#elif defined OS_SOLARIS
	#include <sys/inttypes.h>
#endif
```

**Comment by sgeto** [comment]
Yeah ec_stdint.h is a bit messy. Last time I checked there was a reason for
that if block (Solaris being weird probably). I think I have a patch
somewhere to clean things up a little, but I'm not sure, and I'm not able
to look for it right now.

Have a look at this:
https://stackoverflow.com/questions/1918934/is-u-char-a-standard

To quote:
> u_char is non-standard. If you need to use a standard type that's
equivalent to u_char, you can use uint8_t which is part of the C99 standard
library

I think either typedef'ing it to uint8_t or Alex's approach of simply
getting rid of both of them are the most future proof things to do.

**Comment by kazkansouh** [comment]
That makes sense, thanks.

**Comment by koeppea** [comment]
What about now?

**Comment by kazkansouh** [comment]
Compiles fine now. Thanks :)

**Comment by koeppea** [comment]
@sgeto OK for you?

**Comment by sgeto** [comment]
Yes. Looks good.

**Pull request merged**
