### PR TITLE
Corrected minor typos and improved syntax in a few places.

### PR DESCRIPTION
**Pull request by cmavr8**

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
thanks! merge in a few minutes!

**Comment by gvanem** [comment]
Chris Mavrakis wrote:
>   * Corrected minor typos and improved syntax in a few places.

There are some more. Grep for "wich", "propre", "mesasge" and
"steram".

-- 
--gv

**Comment by cmavr8** [comment]
Well, I only read some sections, I didn't guarantee completeness :)
Anyway, where are the ones you refer to? Grep can't find them

**Comment by LocutusOfBorg** [comment]
fixed in https://github.com/Ettercap/ettercap/commit/142d9a3774aed7163598bf074f7f777de55d0c66

I didn't find any "mesasge" reference

**Comment by gvanem** [comment]
@LocutusOfBorg I didn't find any "mesasge" reference

True, I forgot to pull.
But in ec_log.c there is `the propre header`.
And in ec_text_display.c and el_display.c there is `sync steram/descriptor`.

**Comment by LocutusOfBorg** [comment]
Fixed in d5eb44c93ac6909114d5ed74474e7f11825b65a1
thanks!

**Pull request merged**
