### PR TITLE
Change location of SYSCONFDIR under MacOSX, FreeBSD and Windows

### PR DESCRIPTION
**Pull request by koeppea**
This PR is a fix for #1008 

Well this could be a general question:
/etc is the only exception from all other directories which are all installed under the INSTALL_PREFIX. On the other side, it's quite an habit change that etter.conf would be under /usr/local/etc/ettercap/ even for Linux.

I don't dare doing this step for all platforms.
@eaescob what do you think?

### CODE REVIEW

**Comment by eaescob** [comment]
I agree. We should have everything under install prefix and default to /etc and such. Standardizing regardless of platform makes more sense to me

**Comment by koeppea** [comment]
Should we then at least for etter.conf make an symbolic link if possible 
(on *NIX)?

Otherwise I'm afraid we're getting lots of new issues just because of 
this change.

**Comment by eaescob** [comment]
Yeah, that makes sense. Symlink for some time while people get used to new location. This is awesome work

**Comment by LocutusOfBorg** [comment]
I can't find an easy way for doing symlinks on cmake...

**Comment by koeppea** [comment]
It's only supported on *NIX platforms: https://cmake.org/cmake/help/v3.4/manual/cmake.1.html

> UNIX-specific Command-Line Tools
> 
> The following cmake -E commands are available only on UNIX:
> 
> create_symlink <old> <new>
>     Create a symbolic link <new> naming <old>.
> 
> 

From a pure feeling, I'd limit that to Mac platform only since this platform has performed the  most significant hardening measures of their BSD system.

**Pull request merged**
