### PR TITLE
Replace legacy GeoIP interface with libmaxminddb

### PR DESCRIPTION
**Pull request by koeppea**
This pull request addresses #1202.
The only thing that I'm not sure is, if we are allowed to provide a copy of a GeoLite2 database which I downloaded using my MaxMind account as part of Ettercap installation?
However I read the terms and conditions on MaxMind and I've included the mandatory attribution for using the "GeoLite2 Data". So I think we should be fine.

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
@koeppea aren't files downloadable from here https://github.com/P3TERX/GeoLite.mmdb/releases/tag/2022.12.13 good?

**Comment by LocutusOfBorg** [comment]
Ok for me, looks *really* nice!

**Comment by koeppea** [comment]
Haven’t seen it. Let me have a look at the link.

**Comment by koeppea** [comment]
> aren't files downloadable from here

So in theory they are. But do we want to make the proper installation or download of third-party data make dependent on other Github users?

**Comment by LocutusOfBorg** [comment]
merged, the download of the additional db is free and doesn't need a github account, for me its fine.

**Comment by koeppea** [comment]
Alright. We have the old dependency on the [Webpage](https://www.ettercap-project.org/about.html) and on some Wiki pages.
@LocutusOfBorg When do you think these should get updated?

In my opinion, the safest is to just add the new dependency and once we released, we can remove the obsoleted dependency.

**Comment by LocutusOfBorg** [comment]
yeah, I agree with you!

**Comment by koeppea** [comment]
Webpage and Wiki pages updated

**Pull request merged**
