### PR TITLE
Fix incorrect use of Gtk memory.

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
@koeppea what should we do for
```
./ec_gtk_view_connections.c:          free(row);
./ec_gtk_view_connections.c:       free(row);
./ec_gtk.c:   free(data);
./ec_gtk.c:   free(data);
./ec_gtk.c:   free(data);
./ec_gtk.c:   free(gid->title);
./ec_gtk.c:   free(gid);
./ec_gtk.c:   free(gpd->title);
./ec_gtk.c:   free(gpd);
```
are them dangerous too?

**Comment by koeppea** [comment]
Let me look at it...

**Comment by LocutusOfBorg** [comment]
can we merge? my work on libettercap will make any pull request unmergeable... :)

**Comment by koeppea** [comment]
All the occurances have not been allocated through a *g_\** function, should be freed by the native free call. However I've replaced the calls with the more secure *SAFE_FREE()* macro.
If travis is happy I'm as well.

P.S.
Should we delete the commented code in *ec_gtk.c*?

**Comment by LocutusOfBorg** [comment]
We use git, so I guess we can delete everything, since we already have the code in the history (if needed), but I leave it to you :)

**Comment by koeppea** [comment]
Alright. Deleted.

**Pull request merged**
