### PR TITLE
Don't create empty "desktop" folder if INSTALL_DESKTOP is set to off

### PR DESCRIPTION
**Pull request by sgeto**

### CODE REVIEW

**Comment by eaescob** [comment]
👍

**Comment by LocutusOfBorg** [comment]
ok for me, I would have changed
```
desktop/CMakeLists.txt
```

to remove the if(INSTALL_DESKTOP) check then

**Comment by LocutusOfBorg** [comment]
```diff
--- a/desktop/CMakeLists.txt
+++ b/desktop/CMakeLists.txt
@@ -1,8 +1,8 @@
-if(INSTALL_DESKTOP AND ENABLE_GTK)
+if(ENABLE_GTK)
   configure_file(org.pkexec.ettercap.policy.in
     ${PKEXEC_INSTALL_WRAPPER}.policy @ONLY)
   install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${PKEXEC_INSTALL_WRAPPER}.policy DESTINATION ${POLKIT_DIR})
   install(FILES ettercap.desktop DESTINATION ${DESKTOP_DIR})
   install(FILES ettercap.appdata.xml DESTINATION ${APPDATA_DIR})
   install(PROGRAMS ettercap-pkexec DESTINATION ${INSTALL_BINDIR})
-endif(INSTALL_DESKTOP AND ENABLE_GTK)
+endif(ENABLE_GTK)

```
something like this, but a double check is probably better

**Comment by koeppea** [comment]
@sgeto what do you think about @LocutusOfBorg suggestion?

**Comment by sgeto** [comment]
Makes sense. I didn't look into `desktop/CMakeLists.txt` because I have no use for it. 
The redundant check in `desktop/CMakeLists.txt` should be removed. I'll write a new PR for this.

**Pull request merged**
