### PR TITLE
Update changelog for release

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by koeppea** [comment]
Can we stay under 0.8.3? It's mainly fixes of the features 0.8.3 introduced.
Once we have significant new features or protocol support I'd move to 0.8.4.
This avoids us also from finding a new code name.

**Comment by LocutusOfBorg** [comment]
Yep, the only concern was this snippet:
```
#define EC_VERSION            "0.8.3.1"
#define EC_VERSION_MAJOR      0
#define EC_VERSION_MINOR      8
#define EC_VERSION_REVISION   3
```
so, based on git grep
```
src/ettercap.rc:#define RC_VERSION  EC_VERSION_MAJOR, EC_VERSION_MINOR, EC_VERSION_REVISION, 0
```

something on windows will still see the version as 0.8.3 without the .1 number.

I don't know, maybe we can do something like
#define EC_VERSION_SUBREVISION 1
and define it in ettercap.rc? @gvanem what do you think?

**Comment by LocutusOfBorg** [comment]
this is what I meant
https://github.com/Ettercap/ettercap/pull/1058/commits/b0dc99b624eb6c4df4d68cc7d541f135f1322a39

**Comment by LocutusOfBorg** [comment]
@eaescob is it possible to create a fingerprint.php page on the website?
https://github.com/Ettercap/ettercap/pull/1058/commits/b97d5b9881cfb3fa8ee8e836354dc080306edcda
it should just save some parameters into a file, nothing difficult to do, if we have a php server!
```
   snprintf(getmsg, sizeof(getmsg), "POST %s?finger=%s&os=%s HTTP/1.1\r\n"
                                     "Host: %s\r\n"
                                     "Accept: */*\r\n"
                                     "User-Agent: %s (%s)\r\n"
                                     "\r\n", page, finger, os_encoded, host, EC_GBL_PROGRAM, EC_GBL_VERSION );
```

**Comment by eaescob** [comment]
> @eaescob is it possible to create a fingerprint.php page on the website?
> [b97d5b9](https://github.com/Ettercap/ettercap/commit/b97d5b9881cfb3fa8ee8e836354dc080306edcda)
> it should just save some parameters into a file, nothing difficult to do, if we have a php server!
> 
> ```
>    snprintf(getmsg, sizeof(getmsg), "POST %s?finger=%s&os=%s HTTP/1.1\r\n"
>                                      "Host: %s\r\n"
>                                      "Accept: */*\r\n"
>                                      "User-Agent: %s (%s)\r\n"
>                                      "\r\n", page, finger, os_encoded, host, EC_GBL_PROGRAM, EC_GBL_VERSION );
> ```

We'd need a database for fingerprints right? I can host it on one of my digitalocean VMs.

**Comment by LocutusOfBorg** [comment]
If you want to store the fingerprints database (a plaintext file is probably the best solution), we could also restore the automatic download of the updated db, removed in 
47638bdc985135bccffb284d67dc190d2db122ef

**Comment by LocutusOfBorg** [comment]
@eaescob I opened #1060 to track the update functionality, better don't include in this minor update

**Comment by eaescob** [comment]
> @eaescob I opened #1060 to track the update functionality, better don't include in this minor update

let's think about this for a second. Do we know if this feature is being used? Also, how do we feel about collecting TCP packet fingerprints? Not sure how much of a burden that can put us in.

**Comment by koeppea** [comment]
Just tested. When I use the bundled curl, CURL_FOUND remains OFF and sslstrip plugin is not being built. Even though sslstrip is the main reason why the libcurl dependency is there.

**Comment by LocutusOfBorg** [comment]
@koeppea if you look at travis output, the plugin is there...
https://travis-ci.org/github/Ettercap/ettercap/jobs/708687562

what is your configuration for cmake?

**Comment by koeppea** [comment]
> what is your configuration for cmake?

Reproduced on two computers:
```
$ cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_IPV6=On -DSYSTEM_CURL=Off -DSYSTEM_LIBNET=Off ..
```

**Comment by LocutusOfBorg** [comment]
> > what is your configuration for cmake?
> 
> Reproduced on two computers:
> 
> ```
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_IPV6=On -DSYSTEM_CURL=Off -DSYSTEM_LIBNET=Off ..
> ```

I did the same, but the file is there...
can you please have a look?
http://paste.debian.net/1157398/

I'm trying on debian sid now

**Comment by LocutusOfBorg** [comment]
Same version on Debian minimal chroot without libcurl installed system-wide
http://paste.debian.net/1157400/
am I looking at the wrong plugin filename?

**Comment by LocutusOfBorg** [comment]
> > @eaescob I opened #1060 to track the update functionality, better don't include in this minor update
> 
> let's think about this for a second. Do we know if this feature is being used? Also, how do we feel about collecting TCP packet fingerprints? Not sure how much of a burden that can put us in.

I honestly don't know... we can have it disabled by default, test it internally and see what happens!

**Comment by koeppea** [comment]
@LocutusOfBorg yes you're right. The build files are also present on my machine. But the plugin is not available for activation even though the library file is also present in the target library directory:
```
...
[0]      pptp_clear  1.0  PPTP: Tries to force cleartext tunnel
[0]        pptp_pap  1.0  PPTP: Forces PAP authentication
[0]      pptp_reneg  1.0  PPTP: Forces tunnel re-negotiation
[0]      rand_flood  1.0  Flood the LAN with random MAC addresses
[0]  remote_browser  1.2  Sends visited URLs to the browser
[0]       reply_arp  1.0  Simple arp responder
[0]    repoison_arp  1.0  Repoison after broadcast ARP
[0]   scan_poisoner  1.0  Actively search other poisoners
[0]  search_promisc  1.2  Search promisc NICs in the LAN
[0]       smb_clear  1.0  Tries to force SMB cleartext auth
[0]        smb_down  1.0  Tries to force SMB to not use NTLM2 key auth
[0]    smurf_attack  1.0  Run a smurf attack against specified hosts
[0]     stp_mangler  1.0  Become root of a switches spanning tree


Plugin name (0 to quit): sslstrip

FATAL: sslstrip plugin can not be found !

Closing text interface...


Terminating ettercap...
Unified sniffing was stopped.

koeppea@pinky:/usr/local/lib/ettercap$ ls -lh *sslstr*
-rwxr-xr-x 1 root staff 3,2M Jul 19 22:32 ec_sslstrip.so
koeppea@pinky:/usr/local/lib/ettercap$ 
koeppea@pinky:/usr/local/lib/ettercap$ 
```

**Comment by koeppea** [comment]
Ah... here we go:
```
[     init]     plugin_load_single: /usr/local/lib/ettercap/ec_sslstrip.so
[     init]     plugin_load_single - /usr/local/lib/ettercap/ec_sslstrip.so - dlopen() | /usr/local/lib/ettercap/ec_sslstrip.so: undefined symbol: nghttp2_pack_settings_payload
[     init]     USER_MSG(): plugin ec_sslstrip.so cannot be loaded...

[     init]     plugin ec_sslstrip.so cannot be loaded...
```
Seems it requires a new dependency (_BTW: which is also needed for the HTTP/2 support I'm currently working on_).

**Comment by LocutusOfBorg** [comment]
ok, so this is something that is not yet in master, so a future problem, right?

**Comment by koeppea** [comment]
> so a future problem

Well it's apparently already depending on the new version of the bundled curl package that will come with this subrelease.
So I'd say we have to add this with 0.8.3.1. Maybe as an dependency with a asterisk.

**Comment by LocutusOfBorg** [comment]
does it work better after d088a08c700b6b27c2da67a56d120e9988b312c9 ?

**Comment by koeppea** [comment]
Mhh seems your branch got bit messed up? Github can not list the file changes and the mentioned commit doesn't belong to a known branch. I can also not merge the changes into a test-branch.

**Comment by LocutusOfBorg** [comment]
I had to rebase, because xenial old cmake version was not accepting the find helper I wrote without some syntax changes
96a5054ec1a9a20835184a1ee7aa0156b166e70e

**Comment by koeppea** [comment]
OK. however I cannot merge your changes locally:

```
$ git fetch upstream
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 13 (delta 7), reused 10 (delta 7), pack-reused 0
Entpacke Objekte: 100% (13/13), Fertig.
Von https://github.com/Ettercap/ettercap
   b965207c..96a5054e  refs/pull/1058/head -> upstream/pr/1058
$ git checkout -b test-1058
Zu neuem Branch 'test-1058' gewechselt
$ git merge upstream/pr/1058
warning: refname 'upstream/pr/1058' is ambiguous.
Bereits aktuell.
$ 
```

**Comment by LocutusOfBorg** [comment]
```
git checkout -b test-1058 upstream/pr/1058
Branch 'test-1058' set up to track remote branch 'pr/1058' from 'upstream'.
Switched to a new branch 'test-1058'
```

**Comment by koeppea** [comment]
Mhh totally strange. I even removed upstream and re-added it.. but still the same result. Even when using your command. Let me test using another PC tomorrow morning.

**Comment by LocutusOfBorg** [comment]
@koeppea I suspect, you created locally a branch called "upstream/pr/1058" so, git can't know which one to use.
Maybe something like
git branch -D upstream/pr/1058 might help :)

**Comment by koeppea** [comment]
Oh yes that was the issue. Good catch. Thanks.
Seems the **z** integer conversion of `printf()` is required to avoid the warning on all platforms...... trying now FreeBSD.

**Comment by LocutusOfBorg** [comment]
sorry but isn't "%lu" enough for size_t?

**Comment by LocutusOfBorg** [comment]
Oh, got it, we also already use %zu in src/interfaces/text/ec_text_display.c, introduced in #657

**Comment by koeppea** [comment]
I think we're good then.

**Comment by LocutusOfBorg** [comment]
No more sslstrip issue?

**Comment by koeppea** [comment]
> No more sslstrip issue?

unfortunately the issue is still there. Seems the issue is that libnghttp2 is dynamically linked against libcurl and libcurl is linked against sslstrip plugin.

I tried to add CFLAG `-DNGHTTP2_STATICLIB` to the build wrapper for the bundled curl  package. Sadly with no success.

Here is a hint during installation step of bundled curl:
```
----------------------------------------------------------------------
Libraries have been installed in:
   /home/koeppea/dev/ettercap/build/bundled_deps/curl/bundled-curl-7.71.1-Debug/usr/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
```

The quick and dirty way would be to disable http2 support of curl at configure time.

But I think the correct way would be to link libnghttp2 statically against libcurl.

What do you think?

**Comment by LocutusOfBorg** [comment]
Can you please try this one?
https://github.com/Ettercap/ettercap/pull/1058/commits/49973f652758994f7cfe52b71d031db6aa7e6197

ldd of the ec_sslstrip.so plugin now shows it...

**Comment by LocutusOfBorg** [comment]
ok I did find how to fix it, rebased and pushed

**Comment by LocutusOfBorg** [comment]
I put 20200801 as release date

**Comment by LocutusOfBorg** [comment]
@eaescob I took your commit on branch use-libcurl-fprint-submit, fixed typos, refactored on top of the new fixes, tested with a localhost server successfully and added to this branch as: 05efd31c48ee0ac5e19baa0eba4b50dadebe31eb

**Comment by eaescob** [comment]
@LocutusOfBorg Excellent! I wonder if we should refactor the whole fingerprint system completely to allow folks to configure the URL where they want ettercap to submit fingerprints to. Can we just noop it for now until we decide how to proceed with it?

**Comment by LocutusOfBorg** [comment]
> @LocutusOfBorg Excellent! I wonder if we should refactor the whole fingerprint system completely to allow folks to configure the URL where they want ettercap to submit fingerprints to. Can we just noop it for now until we decide how to proceed with it?

I just did that, I also had to put the old implementation if the curl is not found, to avoid build failures when curl was not found, and plugins were disabled.

**Comment by koeppea** [comment]
> ok I did find how to fix it, rebased and pushed

Works. This was also what I've tested. Disabling HTTP/2 support at configure time. Did 49973f6 not work out?

**Comment by LocutusOfBorg** [comment]
> > ok I did find how to fix it, rebased and pushed
> 
> Works. This was also what I've tested. Disabling HTTP/2 support at configure time. Did [49973f6](https://github.com/Ettercap/ettercap/commit/49973f652758994f7cfe52b71d031db6aa7e6197) not work out?

nope, looks like the ndghttp2 support was required to be inside libcurl.a, not outside, so linking the plugin with it, makes the loader fail when loading the static curl library.

As you said, we have to patch probably the curl library to make it work, something I don't really think its needed!

BTW I added a new commit, to not force-require curl for building plugins

**Comment by koeppea** [comment]
Hi, Franky,

Who is doing the release on GitHub tomorrow?

How about the web site? Shall I take over something?

**Comment by LocutusOfBorg** [comment]
Is it OK to do tomorrow? I can do both no problem! My testing was good

**Comment by eaescob** [comment]
I can make the website changes. What do we need to update with the new release? I can cut the tarball tomorow

**Comment by koeppea** [comment]
> What do we need to update with the new release?

Well merge this PR, create a new Tag and Release, attach the tarball (I think it was only the source w/o the bundled_deps directory). Then update the Website.

This should be it. I guess you take care for the Debian bases Distros. I can write an email to Gentoo and Arch Linux Maintainers.

**Comment by LocutusOfBorg** [comment]
this is how I create a release:
```
# go in master branch
git checkout master
# get new changes
git fetch upstream 
# update local master branch
git merge upstream/master 
# create the tag
git tag v0.8.3.1
# push the tag
git push upstream v0.8.3.1
```

**Comment by LocutusOfBorg** [comment]
after you pushed the tag, the "tag" and tarball are created
https://github.com/Ettercap/ettercap/releases

so, I go there and click on the tag and "create a new release"
copy-paste from CHANGELOG file and from previous releases the legenda
download the tarball, and remove bundled_deps from inside, and reupload for people who needs it (e.g. Debian)

and click publish!

**Comment by LocutusOfBorg** [comment]
and congrats to you all for the release!

**Pull request merged**
